version: '3.8'

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: lumen
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    ports:
        - 15432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/usr/share/postgresql/postgresql.conf  

  php-fpm:
    container_name: php-fpm
    build:
      context: ./php-fpm
    env_file:
      - .env  
    depends_on:
      - db
    volumes:
      - ./../test-app/:/var/www

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ./../test-app/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"




